server:
  port: 8001
spring:
  application:
    name: springcloudservice-config-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://www.eureka7001.com:7001/eureka/, http://www.eureka7002.com:7002/eureka/, http://www.eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloudservice-config-client
    prefer-ip-address: true
---
server:
  port: 8004
spring:
  profiles: dev
  application:
    name: springcloudservice-config-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://www.eureka7001.com:7001/eureka/, http://www.eureka7002.com:7002/eureka/, http://www.eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloudservice-config-client
    prefer-ip-address: true